apiVersion: compute.aws.crossplane.io/v1alpha3
kind: EKSClusterClass
metadata:
  name: ekscluster
specTemplate:
  writeConnectionSecretsToNamespace: crossplane-system
  region: us-east-1
  ## must provide one of roleARN or roleARNRef
  # roleARN: arn:aws:iam::<account-id>:role/<role-name>
  # roleARNRef:
  #   name: sample-eks-cluster-role
  ## must provide one of vpcId or vpcIdRef
  # vpcId: vpc-01
  # vpcIdRef:
  #   name: sample-vpc
  ## must provide one of subnetIds or subnetIdRefs
  # subnetIds:
  # - subnet-01
  # - subnet-02
  # - subnet-03
  # subnetIdRefs:
  # - name: sample-subnet1
  # - name: sample-subnet2
  # - name: sample-subnet3
  ## must provide one of securityGroupIds or securityGroupIdRefs
  # securityGroupIds:
  # - sg-01
  # securityGroupIdRefs:
  # - name: sample-cluster-sg
  workerNodes:
    nodeInstanceType: m3.medium
    nodeGroupName: demo-nodes
    ## must provide one of either clusterControlPlaneSecurityGroup or clusterControlPlaneSecurityGroupRef
    # clusterControlPlaneSecurityGroup: sg-01
    # clusterControlPlaneSecurityGroupRef:
    #   name: sample-cluster-sg
  providerRef:
    name: aws-provider
  reclaimPolicy: Delete
