apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstanceClass
metadata:
  name: rdsinstancepostgresql
specTemplate:
  forProvider:
    dbInstanceClass: db.t2.medium
    masterUsername: masteruser
    allocatedStorage: 50
    engine: postgresql
    skipFinalSnapshotBeforeDeletion: true
  writeConnectionSecretsToNamespace: crossplane-system
  providerRef:
    name: aws-provider
  reclaimPolicy: Delete
